### ISSUE TITLE
Null Pointer in com.group_finity.mascot.generic.GenericEnvironment

### ISSUE THREAD

**Issue by GoogleCodeExporter** [poisonwolfcreations/shimeji-ee#28]
```
How to reproduce:
- 'java -jar ./Shimeji-ee.jar'
- select all, any, or no Shimeji offered

What I expect:
- seeing a Shimeji, or no Shimeji if none were selected

What I see instead:
- the following text on the console:
Exception in thread "main" java.lang.ExceptionInInitializerError

    at com.group_finity.mascot.image.MascotImage.<init>(MascotImage.java:29)
    at com.group_finity.mascot.image.ImagePairLoader.load(ImagePairLoader.java:23)
    at com.group_finity.mascot.config.AnimationBuilder.loadPose(AnimationBuilder.java:58)
    at com.group_finity.mascot.config.AnimationBuilder.<init>(AnimationBuilder.java:41)
    at com.group_finity.mascot.config.ActionBuilder.<init>(ActionBuilder.java:56)
    at com.group_finity.mascot.config.Configuration.load(Configuration.java:45)
    at com.group_finity.mascot.Main.loadConfiguration(Main.java:134)
    at com.group_finity.mascot.Main.run(Main.java:103)
    at com.group_finity.mascot.Main.main(Main.java:83)
Caused by: java.lang.NullPointerException
    at com.group_finity.mascot.generic.GenericEnvironment.tick(GenericEnvironment.java:21)
    at com.group_finity.mascot.environment.Environment.<init>(Environment.java:87)
    at com.group_finity.mascot.generic.GenericEnvironment.<init>(GenericEnvironment.java:14)
    at com.group_finity.mascot.generic.NativeFactoryImpl.<init>(NativeFactoryImpl.java:17)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:532)
    at java.lang.Class.newInstance0(Class.java:372)
    at java.lang.Class.newInstance(Class.java:325)
    at com.group_finity.mascot.NativeFactory.<clinit>(NativeFactory.java:29)
    ... 9 more

If no Shimeji were selected, then it just gives the 
java.lang.NullPointerException, not the 'java.lang.ExceptionInInitializerError' 

```

Original issue reported on code.google.com by `argen...@gmail.com` on 2 Apr 2012 at 1:40

**Comment by GoogleCodeExporter** [comment]
```
Forgot I reported this error... came back to report it again.

Going to give up on this and work on translating the shimeji *.xml & *.png to 
some other application that actually works instead of crashing.
```

Original comment by `argen...@gmail.com` on 8 Jan 2014 at 4:42
